version: '2'
services:
  web:
    build: .
    volumes:
    - .:/usr/app
    container_name: my-web-container
    ports:
      - "80:80"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: someUser
      POSTGRES_DB: myDB

